.PHONY: clean All

All:
	@echo "----------Building project:[ MatrixCalc - Debug ]----------"
	@cd "MatrixCalc" && "$(MAKE)" -f  "MatrixCalc.mk"
clean:
	@echo "----------Cleaning project:[ MatrixCalc - Debug ]----------"
	@cd "MatrixCalc" && "$(MAKE)" -f  "MatrixCalc.mk" clean
